"""
Step 7: Final Composition — Audio + Video Merge
=================================================
Combines lip-synced (and enhanced) video with Hindi audio track.
Handles duration mismatches, codec settings, and metadata.
"""

import subprocess
import shutil
from pathlib import Path
from typing import Optional

from .utils import logger, get_video_info


def compose_final(
    video_path: str,
    audio_path: str,
    output_path: str,
    video_codec: str = "libx264",
    audio_codec: str = "aac",
    crf: int = 18,
) -> str:
    """
    Compose final dubbed video by merging lip-synced video with Hindi audio.

    Args:
        video_path: Path to lip-synced (and optionally enhanced) video
        audio_path: Path to Hindi audio track
        output_path: Path for final output video
        video_codec: Video codec (libx264 recommended)
        audio_codec: Audio codec (aac recommended)
        crf: Constant Rate Factor for quality (18 = visually lossless)

    Returns:
        Path to final composed video
    """
    logger.info("🎬 Composing final dubbed video")
    logger.info(f"   Video source: {video_path}")
    logger.info(f"   Audio source: {audio_path}")

    # Get video info for logging
    try:
        info = get_video_info(video_path)
        logger.info(f"   Resolution: {info.width}x{info.height} @ {info.fps}fps")
    except Exception:
        pass

    # ── Merge video + audio ──────────────────────────────────────
    cmd = [
        "ffmpeg",
        "-y",
        "-i",
        str(video_path),  # Video input
        "-i",
        str(audio_path),  # Hindi audio input
        "-map",
        "0:v:0",  # Take video from first input
        "-map",
        "1:a:0",  # Take audio from second input
        "-c:v",
        video_codec,
        "-preset",
        "slow",  # Better compression
        "-crf",
        str(crf),
        "-c:a",
        audio_codec,
        "-b:a",
        "192k",
        "-ar",
        "44100",  # Standard audio sample rate
        "-ac",
        "2",  # Stereo output
        # Normalize audio to broadcast standard (-14 LUFS)
        "-af",
        "loudnorm=I=-14:LRA=7:TP=-2",
        "-pix_fmt",
        "yuv420p",  # Maximum compatibility
        "-movflags",
        "+faststart",  # Web-optimized MP4
        "-shortest",  # Match shorter stream duration
        "-metadata",
        "title=Hindi Dubbed Video",
        "-metadata",
        "comment=Generated by Supernan AI Pipeline",
        str(output_path),
    ]

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=True,
        )
    except subprocess.CalledProcessError as e:
        logger.error(f"❌ FFmpeg composition failed: {e.stderr[-500:]}")

        # Attempt simpler merge as fallback
        logger.info("   Attempting simple stream copy...")
        return _simple_merge(video_path, audio_path, output_path)

    # ── Verify output ────────────────────────────────────────────
    try:
        output_info = get_video_info(output_path)
        logger.info(f"   ✅ Final output: {output_path}")
        logger.info(
            f"   📊 {output_info.width}x{output_info.height}, "
            f"{output_info.duration:.1f}s, {output_info.file_size_mb}MB"
        )
    except Exception:
        logger.info(f"   ✅ Final output: {output_path}")

    return output_path


def _simple_merge(
    video_path: str,
    audio_path: str,
    output_path: str,
) -> str:
    """Fallback: simple stream copy merge."""
    cmd = [
        "ffmpeg",
        "-y",
        "-i",
        str(video_path),
        "-i",
        str(audio_path),
        "-map",
        "0:v",
        "-map",
        "1:a",
        "-c",
        "copy",
        "-shortest",
        str(output_path),
    ]

    try:
        subprocess.run(cmd, capture_output=True, text=True, check=True)
        logger.info(f"   ✅ Simple merge successful: {output_path}")
        return output_path
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Final merge failed: {e.stderr[-200:]}")


def replace_audio(
    video_path: str,
    audio_path: str,
    output_path: str,
) -> str:
    """
    Replace audio track in video while keeping video stream intact.
    Used when lip-sync is skipped but we still want Hindi audio.

    Args:
        video_path: Original video (video kept as-is)
        audio_path: New Hindi audio track
        output_path: Path for output video

    Returns:
        Path to output video
    """
    logger.info("🔄 Replacing audio track (no lip-sync)")

    cmd = [
        "ffmpeg",
        "-y",
        "-i",
        str(video_path),
        "-i",
        str(audio_path),
        "-map",
        "0:v:0",
        "-map",
        "1:a:0",
        "-c:v",
        "copy",  # Keep video stream as-is
        "-c:a",
        "aac",
        "-b:a",
        "192k",
        "-ar",
        "44100",
        "-ac",
        "2",
        # Normalize audio to broadcast standard
        "-af",
        "loudnorm=I=-14:LRA=7:TP=-2",
        "-shortest",
        str(output_path),
    ]

    try:
        subprocess.run(cmd, capture_output=True, text=True, check=True)
        logger.info(f"   ✅ Audio replaced: {output_path}")
        return output_path
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Audio replacement failed: {e.stderr[-200:]}")


def add_subtitles(
    video_path: str,
    segments: list,
    output_path: str,
    font_size: int = 24,
    font_color: str = "white",
    bg_color: str = "black@0.5",
) -> str:
    """
    Burn Hindi subtitles into video (optional enhancement).

    Args:
        video_path: Input video path
        segments: List of Segment objects with translated text
        output_path: Output video path
        font_size: Subtitle font size
        font_color: Subtitle text color
        bg_color: Subtitle background color

    Returns:
        Path to video with subtitles
    """
    import tempfile

    logger.info("📝 Adding Hindi subtitles")

    # ── Generate SRT subtitle file ──────────────────────────────
    srt_path = tempfile.mktemp(suffix=".srt")
    _generate_srt(segments, srt_path)

    # ── Burn subtitles via ffmpeg ────────────────────────────────
    subtitle_filter = (
        f"subtitles={srt_path}:force_style='"
        f"FontSize={font_size},"
        f"PrimaryColour=&H00FFFFFF,"
        f"OutlineColour=&H00000000,"
        f"Outline=2,"
        f"Shadow=1,"
        f"MarginV=30'"
    )

    cmd = [
        "ffmpeg",
        "-y",
        "-i",
        str(video_path),
        "-vf",
        subtitle_filter,
        "-c:v",
        "libx264",
        "-crf",
        "18",
        "-c:a",
        "copy",
        str(output_path),
    ]

    try:
        subprocess.run(cmd, capture_output=True, text=True, check=True)
        logger.info(f"   ✅ Subtitled video: {output_path}")
    except subprocess.CalledProcessError as e:
        logger.warning(f"   ⚠️  Subtitle burning failed: {e.stderr[-200:]}")
        shutil.copy2(video_path, output_path)
    finally:
        Path(srt_path).unlink(missing_ok=True)

    return output_path


def _generate_srt(segments: list, output_path: str):
    """Generate SRT subtitle file from segments with proper UTF-8 BOM for Hindi."""
    with open(output_path, "w", encoding="utf-8-sig") as f:  # BOM for Devanagari
        for i, seg in enumerate(segments, 1):
            start = _seconds_to_srt_time(seg.start)
            end = _seconds_to_srt_time(seg.end)
            text = seg.translated if seg.translated else seg.text
            f.write(f"{i}\n{start} --> {end}\n{text}\n\n")


def _seconds_to_srt_time(seconds: float) -> str:
    """Convert seconds to SRT timestamp format: HH:MM:SS,mmm"""
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    millis = int((seconds % 1) * 1000)
    return f"{hours:02d}:{minutes:02d}:{secs:02d},{millis:03d}"
